#accepted to commit
import pandas as pd
namafile = input("impor data csv, nama filenya?: ")
data = pd.read_csv(namafile)
print(data)
n = (len(data.values))
x2 = (data['penyebab']**2)
y2 = (data['akibat']**2)
x = (data['penyebab'])
y = (data['akibat'])
xy = (x*y)
sum_x = x.sum()
sum_y = y.sum()
sum_x2 = x2.sum()
sum_y2 = y2.sum()
sum_xy = xy.sum()
a = ((sum_y*sum_x2)-(sum_x*sum_xy))/((n*sum_x2)-((sum_x)**2))
b = ((n*sum_xy)-(sum_x*sum_y))/((n*sum_x2)-((sum_x)**2))
print("x kuadrat: ")
print(x2)
print("y kuadrat: ")
print(y2)
print("x*y: ")
print(xy)
print("sigma x: ", sum_x)
print("sigma y: ", sum_y)
print("sigma x kuadrat: ", sum_x2)
print("sigma y kuadrat: ",sum_y2)
print("sigma x*y: ",sum_xy)
print()
print("a: ", a)
print("b: ",b)
print("model persamaan: Y = ", a, '+',b,'X')
print("ingin prediksi x atau y?: ")
inp = input("[x],[y] ")
if(inp == 'x'):
	inpx = input("masukkan nilai x untuk memprediksi hasil y: ")
	pred_x = a+(b*float(inpx))
	print(pred_x)
if(inp == 'y'):
	inpy = input("masukkan nilai y untuk memprediksi hasil x: ")
	pred_y = (float(inpy)-a)/b
	print(pred_y)

